/**
 * ARTIFURA — Central Information Architecture
 * 8 Major Pages, each containing multiple vertically scrollable Sections.
 */

export const PAGES = [
  {
    index: 0,
    id: 'page-01',
    number: '01',
    slug: 'home',
    title: 'HOME',
    category: 'MANIFESTO',
    position: 'left-top',
    sections: [
      {
        id: 'sec-01-1',
        number: '01.1',
        label: 'MANIFESTO',
        lines: ['WE BUILD', 'WHAT COMES NEXT.'],
        subtitle: 'ARTIFURA // TECHNOLOGY COMPANY',
      },
      {
        id: 'sec-01-2',
        number: '01.2',
        label: 'THESIS',
        lines: ['IDEAS DESERVE', 'TO BECOME REAL.'],
        subtitle: 'CONVERGENCE // REALIZATION',
      },
      {
        id: 'sec-01-3',
        number: '01.3',
        label: 'PRINCIPLE',
        lines: ['LESS UI,', 'MORE EXPERIENCE.'],
        subtitle: 'ARCHITECTURAL INTENT // EMPTINESS',
      },
    ],
  },
  {
    index: 1,
    id: 'page-02',
    number: '02',
    slug: 'philosophy',
    title: 'PHILOSOPHY',
    category: 'DOCTRINE',
    position: 'left-bottom',
    sections: [
      {
        id: 'sec-02-1',
        number: '02.1',
        label: 'SYSTEMS',
        lines: ['WE TURN', 'COMPLEXITY', 'INTO SYSTEMS.'],
        subtitle: 'TOPOLOGY: ADAPTIVE MESH',
        hasNetworkCanvas: true,
      },
      {
        id: 'sec-02-2',
        number: '02.2',
        label: 'STRUCTURE',
        lines: ['ELEGANCE', 'THROUGH RIGOR.'],
        subtitle: 'ORDER OUT OF ENTROPY',
      },
      {
        id: 'sec-02-3',
        number: '02.3',
        label: 'FOUNDATION',
        lines: ['ENGINEERED FOR', 'THE WORLD AHEAD.'],
        subtitle: 'DETERMINISTIC PRECISION',
      },
    ],
  },
  {
    index: 2,
    id: 'page-03',
    number: '03',
    slug: 'services',
    title: 'SERVICES',
    category: 'CAPABILITIES',
    position: 'bottom-1',
    sections: [
      {
        id: 'sec-03-1',
        number: '03.1',
        label: 'DISCIPLINES',
        lines: ['ENGINEERED', 'FOR TOMORROW.'],
        subtitle: 'PRIMARY CAPABILITY DOMAINS',
      },
      {
        id: 'sec-03-2',
        number: '03.2',
        label: 'WEB SYSTEMS',
        lines: ['HIGH-PERFORMANCE', 'INTERACTION WEB.'],
        subtitle: 'REACT // WEBGL // SPATIAL PROTOCOLS',
      },
      {
        id: 'sec-03-3',
        number: '03.3',
        label: 'AI INFRASTRUCTURE',
        lines: ['COGNITIVE MESH', '& NEURAL EMBEDDINGS.'],
        subtitle: 'AI COMPILATION // VECTOR RETRIEVAL',
      },
      {
        id: 'sec-03-4',
        number: '03.4',
        label: 'ENTERPRISE',
        lines: ['FAULT-TOLERANT', 'DISTRIBUTED ARCHITECTURE.'],
        subtitle: 'HIGH-THROUGHPUT COMPILATION',
      },
    ],
  },
  {
    index: 3,
    id: 'page-04',
    number: '04',
    slug: 'stack',
    title: 'STACK',
    category: 'INSTRUMENTATION',
    position: 'bottom-2',
    sections: [
      {
        id: 'sec-04-1',
        number: '04.1',
        label: 'INSTRUMENTATION',
        lines: ['BUILT WITH', 'THE RIGHT TOOLS.'],
        subtitle: 'CORE SELECTION // 01-06',
        hasStackCycler: true,
      },
      {
        id: 'sec-04-2',
        number: '04.2',
        label: 'ARCHITECTURE',
        lines: ['PYTHON // DJANGO', 'REACT // .NET // AI'],
        subtitle: 'DISTRIBUTED EXECUTION // COMPILATION',
      },
      {
        id: 'sec-04-3',
        number: '04.3',
        label: 'INFRASTRUCTURE',
        lines: ['CLOUD-NATIVE', 'SERVERLESS FABRIC.'],
        subtitle: 'SUB-MILLISECOND GLOBAL DISPATCH',
      },
    ],
  },
  {
    index: 4,
    id: 'page-05',
    number: '05',
    slug: 'work',
    title: 'WORK',
    category: 'OUTPUT',
    position: 'bottom-3',
    sections: [
      {
        id: 'sec-05-1',
        number: '05.1',
        label: 'ARTIFACTS',
        lines: ['WE MAKE THINGS', 'THAT WORK.'],
        subtitle: 'PROVEN SYSTEM DEPLOYMENTS',
        hasProjects: true,
      },
      {
        id: 'sec-05-2',
        number: '05.2',
        label: 'CASE EVIDENCE',
        lines: ['DIGITAL SYSTEMS', 'IN PRODUCTION.'],
        subtitle: '0.4MS FRAME TIME // ZERO LATENCY',
      },
      {
        id: 'sec-05-3',
        number: '05.3',
        label: 'DEPLOYMENT',
        lines: ['SCALED ENTERPRISE', 'ORCHESTRATION.'],
        subtitle: '120,000 EVENTS/SEC // 99.999% SLA',
      },
    ],
  },
  {
    index: 5,
    id: 'page-06',
    number: '06',
    slug: 'approach',
    title: 'APPROACH',
    category: 'METHOD',
    position: 'bottom-4',
    sections: [
      {
        id: 'sec-06-1',
        number: '06.1',
        label: 'METHODOLOGY',
        lines: ['THINK. DESIGN.', 'ENGINEER. REPEAT.'],
        subtitle: 'CYCLE: ITERATIVE PRECISION',
        hasBeam: true,
      },
      {
        id: 'sec-06-2',
        number: '06.2',
        label: 'PHILOSOPHY OF CRAFT',
        lines: ['MEASURE TWICE.', 'BUILD ONCE.'],
        subtitle: 'MINIMAL FRICTION // MAXIMUM RIGOR',
      },
      {
        id: 'sec-06-3',
        number: '06.3',
        label: 'EXECUTION',
        lines: ['DISCIPLINE IN', 'EVERY DETAIL.'],
        subtitle: 'ARCHITECTURAL INTEGRITY',
      },
    ],
  },
  {
    index: 6,
    id: 'page-07',
    number: '07',
    slug: 'company',
    title: 'COMPANY',
    category: 'IDENTITY',
    position: 'right-top',
    sections: [
      {
        id: 'sec-07-1',
        number: '07.1',
        label: 'IDENTITY',
        lines: ['ARTIFURA IS A', 'TECHNOLOGY COMPANY', 'BUILDING WHAT COMES NEXT.'],
        subtitle: 'EST. 2026 // BENGALURU, INDIA',
      },
      {
        id: 'sec-07-2',
        number: '07.2',
        label: 'DOCTRINE',
        lines: ['QUIET ELEGANCE.', 'UNCOMPROMISING SPEED.'],
        subtitle: 'CORE PRINCIPLES // ARTIFURA LABS',
      },
      {
        id: 'sec-07-3',
        number: '07.3',
        label: 'VISION',
        lines: ['SHAPING THE', 'DIGITAL HORIZON.'],
        subtitle: 'INDEPENDENT TECHNOLOGY STUDIO',
      },
    ],
  },
  {
    index: 7,
    id: 'page-08',
    number: '08',
    slug: 'contact',
    title: 'CONTACT',
    category: 'TRANSMISSION',
    position: 'right-bottom',
    sections: [
      {
        id: 'sec-08-1',
        number: '08.1',
        label: 'TRANSMISSION',
        lines: ['HAVE SOMETHING', 'WORTH BUILDING?'],
        subtitle: 'DIRECT INQUIRY // HELLO@ARTIFURA.COM',
        hasContactCta: true,
      },
      {
        id: 'sec-08-2',
        number: '08.2',
        label: 'CHANNELS',
        lines: ['COMMUNICATIONS', 'OPEN 2026.'],
        subtitle: 'BENGALURU, INDIA // GLOBAL DISPATCH',
      },
      {
        id: 'sec-08-3',
        number: '08.3',
        label: 'END OF TRANSMISSION',
        lines: ['PRECISION // OPTICAL', 'ARTIFURA ALLIANCE.'],
        subtitle: 'ALL RIGHTS RESERVED // 2026',
      },
    ],
  },
];
