/**
 * ARTIFURA — Central Section Configuration
 * Defines all 8 sections, their numbers, labels, lines, seeds, and perimeter positions.
 */

export const SECTIONS = [
  {
    index: 0,
    number: '01',
    id: 'section-01',
    slug: 'overview',
    title: 'WE BUILD WHAT COMES NEXT',
    lines: ['WE BUILD', 'WHAT COMES NEXT.'],
    position: 'left-top',
    seed: 1,
    telemetryLeft: 'ARTIFURA // TECHNOLOGY COMPANY',
    telemetryRight: 'SECTION 01 // OVERVIEW',
    telemetryBottom: 'SCROLL OR SELECT TO NAVIGATE ↓',
  },
  {
    index: 1,
    number: '02',
    id: 'section-02',
    slug: 'about',
    title: 'IDEAS DESERVE TO BECOME REAL',
    lines: ['IDEAS DESERVE', 'TO BECOME REAL.'],
    position: 'left-bottom',
    seed: 3,
    telemetryLeft: '02 // THESIS',
    telemetryRight: 'OPTICAL DISPLACEMENT: ACTIVE',
    telemetryBottom: 'CONVERGENCE // REALIZATION',
  },
  {
    index: 2,
    number: '03',
    id: 'section-03',
    slug: 'services',
    title: 'WE TURN COMPLEXITY INTO SYSTEMS',
    lines: ['WE TURN', 'COMPLEXITY', 'INTO SYSTEMS.'],
    position: 'bottom-1',
    seed: 5,
    telemetryLeft: '03 // ARCHITECTURE',
    telemetryRight: 'TOPOLOGY: ADAPTIVE MESH',
    telemetryBottom: 'STRUCTURE // ORCHESTRATION',
  },
  {
    index: 3,
    number: '04',
    id: 'section-04',
    slug: 'stack',
    title: 'BUILT WITH THE RIGHT TOOLS',
    lines: ['BUILT WITH', 'THE RIGHT TOOLS.'],
    position: 'bottom-2',
    seed: 7,
    telemetryLeft: '04 // INSTRUMENTATION',
    telemetryRight: 'STACK // REFINEMENT',
    telemetryBottom: 'PRECISION SELECTION // 01-06',
  },
  {
    index: 4,
    number: '05',
    id: 'section-05',
    slug: 'work',
    title: 'WE MAKE THINGS THAT WORK',
    lines: ['WE MAKE THINGS', 'THAT WORK.'],
    position: 'bottom-3',
    seed: 9,
    telemetryLeft: '05 // ARTIFACTS',
    telemetryRight: 'STATUS: PROVEN ARCHITECTURE',
    telemetryBottom: 'CLICK IDENTIFIER FOR TECHNICAL ARCHIVE',
  },
  {
    index: 5,
    number: '06',
    id: 'section-06',
    slug: 'approach',
    title: 'THINK. DESIGN. ENGINEER. REPEAT.',
    lines: ['THINK. DESIGN.', 'ENGINEER. REPEAT.'],
    position: 'bottom-4',
    seed: 11,
    telemetryLeft: '06 // METHODOLOGY',
    telemetryRight: 'CYCLE: ITERATIVE PRECISION',
    telemetryBottom: 'DISCIPLINE // CONTINUOUS COMPOSITION',
  },
  {
    index: 6,
    number: '07',
    id: 'section-07',
    slug: 'network',
    title: 'ARTIFURA IS A TECHNOLOGY COMPANY',
    lines: ['ARTIFURA IS A', 'TECHNOLOGY COMPANY', 'BUILDING WHAT COMES NEXT.'],
    position: 'right-top',
    seed: 13,
    telemetryLeft: '07 // IDENTITY',
    telemetryRight: 'INDEPENDENT ENTITY',
    telemetryBottom: 'CORE DOCTRINE // ARTIFURA LABS',
  },
  {
    index: 7,
    number: '08',
    id: 'section-08',
    slug: 'contact',
    title: 'HAVE SOMETHING WORTH BUILDING?',
    lines: ['HAVE SOMETHING', 'WORTH BUILDING?'],
    position: 'right-bottom',
    seed: 15,
    telemetryLeft: '08 // TRANSMISSION',
    telemetryRight: 'CHANNEL: DIRECT INQUIRY',
    telemetryBottom: 'ARTIFURA // BENGALURU, INDIA // END OF MANIFESTO',
  },
];
